'use client';

// Key Insights — the deterministic findings of the period, ranked.
// Every insight is generated by a documented rule in lib/performance/insights
// and links back to the data that produced it (goal / project / day filter).

import { useState } from 'react';
import { AlertTriangle, ChevronRight, Database, Info, TrendingUp } from 'lucide-react';
import type { PerformanceInsight } from '@/lib/performance/types';
import { INSIGHT_META } from './theme';

/** Insights shown before the "Show more" toggle. */
const INITIAL_VISIBLE = 4;

interface InsightsPanelProps {
  insights: PerformanceInsight[];
  onApplyLink: (insight: PerformanceInsight) => void;
}

function InsightIcon({ kind }: { kind: PerformanceInsight['kind'] }) {
  const className = `w-4 h-4 ${INSIGHT_META[kind].iconClassName}`;
  if (kind === 'positive') return <TrendingUp className={className} aria-hidden="true" />;
  if (kind === 'warning') return <AlertTriangle className={className} aria-hidden="true" />;
  if (kind === 'data-quality') return <Database className={className} aria-hidden="true" />;
  return <Info className={className} aria-hidden="true" />;
}

const KIND_LABEL: Record<PerformanceInsight['kind'], string> = {
  positive: 'Positive',
  warning: 'Warning',
  information: 'Info',
  'data-quality': 'Data quality',
};

export default function InsightsPanel({ insights, onApplyLink }: InsightsPanelProps) {
  const [showAll, setShowAll] = useState(false);
  const visible = showAll ? insights : insights.slice(0, INITIAL_VISIBLE);
  const hiddenCount = insights.length - visible.length;
  return (
    <section
      aria-label="Key insights"
      className="rounded-2xl border border-slate-200 bg-white p-4 sm:p-5"
      data-testid="insights-panel"
    >
      <div className="mb-3">
        <h3 className="text-sm font-bold text-slate-900">What changed</h3>
        <p className="text-xs text-slate-500">
          Deterministic findings computed from this period&apos;s data — no AI, every rule documented
        </p>
      </div>

      {insights.length === 0 ? (
        <p className="text-sm text-slate-400 py-4 text-center">
          Nothing notable — the period matches its plan within thresholds.
        </p>
      ) : (
        <ul className="space-y-2">
          {visible.map((insight) => {
            const meta = INSIGHT_META[insight.kind];
            const clickable = insight.link !== undefined;
            const body = (
              <>
                <span className="mt-0.5 shrink-0" aria-hidden="true">
                  <InsightIcon kind={insight.kind} />
                </span>
                <span className="min-w-0 flex-1">
                  <span
                    className="block text-[13px] font-semibold text-slate-900 leading-snug line-clamp-2"
                    title={insight.title}
                  >
                    {insight.title}
                  </span>
                  <span
                    className="block text-xs text-slate-500 mt-0.5 line-clamp-2"
                    title={insight.description}
                  >
                    {insight.description}
                  </span>
                </span>
                <span className="sr-only">{KIND_LABEL[insight.kind]}</span>
                {clickable && (
                  <ChevronRight className="w-4 h-4 text-slate-300 shrink-0 mt-0.5" aria-hidden="true" />
                )}
              </>
            );
            return (
              <li key={insight.id}>
                {clickable ? (
                  <button
                    type="button"
                    data-testid={`insight-${insight.rule}`}
                    onClick={() => onApplyLink(insight)}
                    className={`w-full text-left flex items-start gap-2.5 rounded-xl border px-3 py-2.5 transition-colors hover:brightness-[0.98] ${meta.className}`}
                  >
                    {body}
                  </button>
                ) : (
                  <div
                    data-testid={`insight-${insight.rule}`}
                    className={`flex items-start gap-2.5 rounded-xl border px-3 py-2.5 ${meta.className}`}
                  >
                    {body}
                  </div>
                )}
              </li>
            );
          })}
        </ul>
      )}

      {(hiddenCount > 0 || showAll) && insights.length > INITIAL_VISIBLE && (
        <button
          type="button"
          onClick={() => setShowAll((v) => !v)}
          className="mt-2.5 w-full text-center text-xs font-semibold text-blue-700 hover:text-blue-800 py-1.5 rounded-lg hover:bg-blue-50 transition-colors"
          data-testid="insights-toggle"
        >
          {showAll ? 'Show fewer' : `Show ${hiddenCount} more`}
        </button>
      )}
    </section>
  );
}
