// src/lib/goalArchitect/fixtures.ts
// Hand-built `GoalArchitectureDraft` fixtures for the user's five real goals.
//
// These exist so:
//   1. Tests can assert the validation/summary core against realistic data.
//   2. Prompt 2 (parser) has a target shape to compile *into*.
//   3. Prompt 3 (UI) has draft data to render before the parser is wired.
//
// No parser is involved — every entity is constructed directly. Ids come
// from `createDraftId` so they remain stable across runs.

import { createDraftId } from './ids';
import { calculateGoalArchitectureSummary } from './summary';
import {
  GOAL_ARCHITECT_DRAFT_VERSION,
  type DraftConfidence,
  type GoalArchitectureDraft,
  type GoalDraft,
  type KeyResultDraft,
  type ProjectDraft,
  type TaskDraft,
} from './types';

// ============================================================================
// SHARED HELPERS
// ============================================================================

/**
 * Stable timestamp used for fixture `createdAt`/`updatedAt`. Real drafts
 * generated by the parser will use the current ISO time, but for fixtures we
 * want byte-identical equality across test runs.
 */
const FIXTURE_TIMESTAMP_ISO = '2026-01-01T00:00:00.000Z';
const FIXTURE_YEAR_END_ISO = '2026-12-31';

const FULL_CONFIDENCE: DraftConfidence = {
  overall: 0.92,
  title: { value: 1, reason: 'Title supplied verbatim in fixture.' },
  hours: { value: 0.9, reason: 'Hours estimated from user spec.' },
  dueDate: { value: 0.95, reason: 'Hard deadline supplied.' },
  priority: { value: 0.85, reason: 'Priority inferred from category.' },
  hierarchy: { value: 0.95, reason: 'Hand-curated parent-child links.' },
};

interface TaskSpec {
  title: string;
  hours: number;
  description?: string;
}

interface ProjectSpec {
  title: string;
  description?: string;
  targetHours: number;
  tasks: TaskSpec[];
}

interface KeyResultSpec {
  title: string;
  targetValue: number;
  unit: KeyResultDraft['unit'];
  description?: string;
}

interface GoalSpec {
  title: string;
  description: string;
  targetHours: number;
  projects: ProjectSpec[];
  keyResults: KeyResultSpec[];
}

function buildKeyResult(
  spec: KeyResultSpec,
  parentGoalId: string,
): KeyResultDraft {
  return {
    id: createDraftId('key_result', spec.title, parentGoalId),
    title: spec.title,
    description: spec.description,
    targetValue: spec.targetValue,
    currentValue: 0,
    unit: spec.unit,
    parentGoalId,
    sourceText: spec.title,
    confidence: FULL_CONFIDENCE,
  };
}

function buildTask(
  spec: TaskSpec,
  parentGoalId: string,
  parentProjectId: string,
): TaskDraft {
  return {
    id: createDraftId('task', spec.title, parentProjectId),
    title: spec.title,
    description: spec.description,
    estimatedHours: spec.hours,
    dueDateISO: FIXTURE_YEAR_END_ISO,
    priority: 'high',
    parentGoalId,
    parentProjectId,
    sourceText: spec.title,
    confidence: FULL_CONFIDENCE,
  };
}

function buildProject(
  spec: ProjectSpec,
  parentGoalId: string,
): { project: ProjectDraft; tasks: TaskDraft[] } {
  const projectId = createDraftId('project', spec.title, parentGoalId);
  const tasks = spec.tasks.map((t) => buildTask(t, parentGoalId, projectId));
  const project: ProjectDraft = {
    id: projectId,
    title: spec.title,
    description: spec.description,
    targetHours: spec.targetHours,
    dueDateISO: FIXTURE_YEAR_END_ISO,
    priority: 'high',
    parentGoalId,
    taskIds: tasks.map((t) => t.id),
    sourceText: spec.title,
    confidence: FULL_CONFIDENCE,
  };
  return { project, tasks };
}

function buildGoalArchitecture(spec: GoalSpec): GoalArchitectureDraft {
  const goalId = createDraftId('goal', spec.title);

  const projects: ProjectDraft[] = [];
  const tasks: TaskDraft[] = [];
  for (const ps of spec.projects) {
    const built = buildProject(ps, goalId);
    projects.push(built.project);
    tasks.push(...built.tasks);
  }
  const keyResults = spec.keyResults.map((krs) => buildKeyResult(krs, goalId));

  const goal: GoalDraft = {
    id: goalId,
    title: spec.title,
    description: spec.description,
    targetHours: spec.targetHours,
    dueDateISO: FIXTURE_YEAR_END_ISO,
    priority: 'critical',
    projectIds: projects.map((p) => p.id),
    directTaskIds: [],
    keyResultIds: keyResults.map((kr) => kr.id),
    sourceText: spec.title,
    confidence: FULL_CONFIDENCE,
  };

  const draftWithoutDerived: GoalArchitectureDraft = {
    id: createDraftId('goal', `${spec.title}__architecture`),
    version: GOAL_ARCHITECT_DRAFT_VERSION,
    status: 'draft',
    createdAtISO: FIXTURE_TIMESTAMP_ISO,
    updatedAtISO: FIXTURE_TIMESTAMP_ISO,
    sourceText: spec.title,
    goal,
    projects,
    tasks,
    keyResults,
    issues: [],
    summary: {
      goalCount: 0,
      projectCount: 0,
      taskCount: 0,
      keyResultCount: 0,
      totalProjectTargetHours: 0,
      totalTaskEstimatedHours: 0,
      orphanTaskCount: 0,
      orphanKeyResultCount: 0,
      errorCount: 0,
      warningCount: 0,
      infoCount: 0,
      isStructurallyValid: false,
      canCommit: false,
    },
    confidence: FULL_CONFIDENCE,
  };

  // Compute summary with empty issues — validation can be re-run by callers
  // who need fresh issues, but fixtures should expose consistent counters.
  draftWithoutDerived.summary = calculateGoalArchitectureSummary(
    draftWithoutDerived,
    { issues: [] },
  );

  return draftWithoutDerived;
}

// ============================================================================
// 1. LAVORO — Career Command 2026
// ============================================================================

export function createWorkGoalDraftFixture(): GoalArchitectureDraft {
  return buildGoalArchitecture({
    title: 'LAVORO — Career Command 2026',
    description:
      'Trasformare Life Tracker e i materiali professionali in un sistema operativo per ottenere ruoli SaaS/Data/Ops e UN/FAO entro fine 2026.',
    targetHours: 400,
    projects: [
      {
        title: 'Career Command Center',
        targetHours: 40,
        tasks: [
          { title: 'Strutturare dashboard candidature settimanali', hours: 10 },
          { title: 'Definire OKR Carriera 2026', hours: 10 },
          { title: 'Mappa contatti, referenti e introduzioni', hours: 20 },
        ],
      },
      {
        title: 'CV, Documenti e Application Materials',
        targetHours: 50,
        tasks: [
          { title: 'Finalizzare pacchetto CV principale', hours: 15 },
          { title: 'Preparare cover letter master', hours: 15 },
          { title: 'Aggiornare CV in formato UN P11', hours: 20 },
        ],
      },
      {
        title: 'GitHub & Portfolio',
        targetHours: 60,
        tasks: [
          { title: 'Trasformare Life Tracker in case study portfolio', hours: 30 },
          { title: 'Pubblicare 3 repository di esempio', hours: 30 },
        ],
      },
      {
        title: 'LinkedIn & Professional Brand',
        targetHours: 40,
        tasks: [
          { title: 'Riscrivere headline e about LinkedIn', hours: 10 },
          { title: 'Pubblicare 12 post tecnici', hours: 30 },
        ],
      },
      {
        title: 'Candidature mirate SaaS, Data, Ops',
        targetHours: 70,
        tasks: [
          { title: 'Identificare top 30 aziende target', hours: 20 },
          { title: 'Inviare candidature mirate', hours: 50 },
        ],
      },
      {
        title: 'ONU, FAO, WFP, IFAD, UNV, UNOPS',
        targetHours: 60,
        tasks: [
          { title: 'Completare profili ufficiali FAO/UN', hours: 30 },
          { title: 'Tracciare bandi UN Talent Pool', hours: 30 },
        ],
      },
      {
        title: 'Networking, Colloqui e STAR Stories',
        targetHours: 50,
        tasks: [
          { title: 'Creare STAR Stories Master Bank', hours: 25 },
          { title: 'Simulare 10 colloqui registrati', hours: 25 },
        ],
      },
      {
        title: 'Skills & Certificazioni',
        targetHours: 30,
        tasks: [
          { title: 'Completare certificazione PMP foundations', hours: 15 },
          { title: 'Completare corso advanced SQL', hours: 15 },
        ],
      },
    ],
    keyResults: [
      {
        title: '120 candidature mirate inviate',
        targetValue: 120,
        unit: 'tasks',
      },
      {
        title: '20 colloqui condotti',
        targetValue: 20,
        unit: 'sessions',
      },
      {
        title: '1 offerta di lavoro firmata',
        targetValue: 1,
        unit: 'tasks',
      },
    ],
  });
}

// ============================================================================
// 2. SCACCHI — Chess Mastery
// ============================================================================

export function createChessGoalDraftFixture(): GoalArchitectureDraft {
  return buildGoalArchitecture({
    title: 'SCACCHI — Chess Mastery',
    description:
      'Costruire una base strutturata di calcolo, tattica, aperture, strategia e finali per arrivare a un livello competitivo solido.',
    targetHours: 300,
    projects: [
      {
        title: 'Calcolo e Visualizzazione',
        targetHours: 80,
        tasks: [
          { title: 'Completare Cognitive Chess Training — 20 giorni', hours: 40 },
          { title: 'Completare 100 studi essenziali alla cieca', hours: 40 },
        ],
      },
      {
        title: 'Tattica',
        targetHours: 60,
        tasks: [
          { title: 'Risolvere 2000 puzzle tattici curati', hours: 40 },
          { title: 'Studiare pattern di sacrificio classici', hours: 20 },
        ],
      },
      {
        title: 'Aperture',
        targetHours: 60,
        tasks: [
          { title: 'Completare Short & Sweet Catalana', hours: 20 },
          { title: 'Studiare Fighting Like Magnus in the Sicilian (Sveshnikov)', hours: 25 },
          { title: 'Studiare repertorio nero con Benko Gambit', hours: 15 },
        ],
      },
      {
        title: 'Strategia',
        targetHours: 60,
        tasks: [
          { title: 'Completare How to Reassess Your Chess', hours: 35 },
          { title: 'Analizzare 50 partite di Karpov annotate', hours: 25 },
        ],
      },
      {
        title: 'Finali',
        targetHours: 40,
        tasks: [
          { title: 'Studiare Dvoretsky Endgame Manual — capitoli base', hours: 25 },
          { title: 'Risolvere 200 studi di finale', hours: 15 },
        ],
      },
    ],
    keyResults: [
      { title: 'Raggiungere 2000 Elo online stabile', targetValue: 2000, unit: 'percent' },
      { title: 'Completare 2000 puzzle tattici tracciati', targetValue: 2000, unit: 'studies' },
      { title: 'Studiare 4 corsi Chessable', targetValue: 4, unit: 'courses' },
    ],
  });
}

// ============================================================================
// 3. MODEL PHYSIQUE
// ============================================================================

export function createModelPhysiqueGoalDraftFixture(): GoalArchitectureDraft {
  return buildGoalArchitecture({
    title: 'MODEL PHYSIQUE — Corpo estetico, forte e definito',
    description:
      'Costruire un fisico estetico, forte e definito attraverso allenamento, nutrizione, condizionamento e recupero.',
    targetHours: 350,
    projects: [
      {
        title: 'Allenamento Ipertrofia',
        targetHours: 150,
        tasks: [
          { title: 'Costruire scheda allenamento 4 giorni', hours: 10 },
          { title: 'Eseguire 48 sedute di ipertrofia trimestrali', hours: 140 },
        ],
      },
      {
        title: 'Nutrizione',
        targetHours: 60,
        tasks: [
          { title: 'Definire calorie e macronutrienti', hours: 10 },
          { title: 'Tenere food log settimanale', hours: 50 },
        ],
      },
      {
        title: 'Condizionamento',
        targetHours: 60,
        tasks: [
          { title: 'Costruire piano cardio LISS + HIIT', hours: 10 },
          { title: 'Eseguire 50 sedute di condizionamento', hours: 50 },
        ],
      },
      {
        title: 'Recupero, Mobilità e Postura',
        targetHours: 40,
        tasks: [
          { title: 'Routine mobility 4x settimana', hours: 25 },
          { title: 'Programma di stretching posturale', hours: 15 },
        ],
      },
      {
        title: 'Tracking Fisico',
        targetHours: 40,
        tasks: [
          { title: 'Creare baseline fisica iniziale', hours: 10 },
          { title: 'Fare review fisica settimanale', hours: 30 },
        ],
      },
    ],
    keyResults: [
      { title: 'Raggiungere 12% di body fat misurato', targetValue: 12, unit: 'percent' },
      { title: 'Completare 200 sedute totali nell\'anno', targetValue: 200, unit: 'sessions' },
      { title: 'Pubblicare 4 review fisiche trimestrali', targetValue: 4, unit: 'studies' },
    ],
  });
}

// ============================================================================
// 4. INTELLIGENCE ENGINE
// ============================================================================

export function createIntelligenceEngineGoalDraftFixture(): GoalArchitectureDraft {
  return buildGoalArchitecture({
    title: 'INTELLIGENCE ENGINE — sviluppo mentale, lettura e apprendimento',
    description:
      'Costruire un sistema personale di lettura strategica, note attive, ripetizione spaziata e scrittura per moltiplicare la capacità di apprendere.',
    targetHours: 280,
    projects: [
      {
        title: 'Lettura strategica',
        targetHours: 100,
        tasks: [
          { title: 'Creare lista libri prioritari', hours: 5 },
          { title: 'Completare primo libro con note', hours: 35 },
          { title: 'Completare 6 libri tracciati', hours: 60 },
        ],
      },
      {
        title: 'Note attive e sintesi',
        targetHours: 50,
        tasks: [
          { title: 'Trasformare appunti in insight operativi', hours: 30 },
          { title: 'Creare review mensile delle note', hours: 20 },
        ],
      },
      {
        title: 'Anki / spaced repetition',
        targetHours: 50,
        tasks: [
          { title: 'Creare card Anki dei concetti chiave', hours: 20 },
          { title: 'Mantenere streak Anki 5x settimana', hours: 30 },
        ],
      },
      {
        title: 'NotebookLM / knowledge system',
        targetHours: 40,
        tasks: [
          { title: 'Configurare workspace NotebookLM', hours: 10 },
          { title: 'Importare e indicizzare 20 fonti chiave', hours: 30 },
        ],
      },
      {
        title: 'Scrittura e ragionamento',
        targetHours: 40,
        tasks: [
          { title: 'Pubblicare 12 essay personali', hours: 30 },
          { title: 'Tenere journal analitico settimanale', hours: 10 },
        ],
      },
    ],
    keyResults: [
      { title: '12 libri letti con note', targetValue: 12, unit: 'books' },
      { title: '500 card Anki attive', targetValue: 500, unit: 'studies' },
      { title: '12 essay pubblicati', targetValue: 12, unit: 'tasks' },
    ],
  });
}

// ============================================================================
// 5. PRESENCE UPGRADE
// ============================================================================

export function createPresenceUpgradeGoalDraftFixture(): GoalArchitectureDraft {
  return buildGoalArchitecture({
    title: 'PRESENCE UPGRADE — look, voce, carisma e immagine',
    description:
      'Aumentare presenza personale, fiducia e comunicazione tramite postura, voce, carisma, look e mindset.',
    targetHours: 220,
    projects: [
      {
        title: 'Postura, Body Language & Presenza Fisica',
        targetHours: 30,
        tasks: [
          { title: 'Routine posturale quotidiana 10 min', hours: 15 },
          { title: 'Eseguire 20 sessioni di feedback video posturale', hours: 15 },
        ],
      },
      {
        title: 'Voce, Intonazione & Comunicazione Orale',
        targetHours: 40,
        tasks: [
          { title: 'Creare routine voce e respirazione', hours: 15 },
          { title: 'Registrare pitch e conversazioni simulate', hours: 25 },
        ],
      },
      {
        title: 'Carisma, Self-Esteem & Social Presence',
        targetHours: 40,
        tasks: [
          { title: 'Completare corso Confidence and Self Esteem', hours: 20 },
          { title: 'Praticare 20 interazioni sociali calibrate', hours: 20 },
        ],
      },
      {
        title: 'Lookmaxing, Grooming & Immagine Personale',
        targetHours: 30,
        tasks: [
          { title: 'Definire wardrobe capsule', hours: 15 },
          { title: 'Costruire routine grooming settimanale', hours: 15 },
        ],
      },
      {
        title: 'Public Image & Personal Brand',
        targetHours: 40,
        tasks: [
          { title: 'Rinnovare profili social per coerenza brand', hours: 15 },
          { title: 'Realizzare shooting personale professionale', hours: 25 },
        ],
      },
      {
        title: 'Mindset, Visualizzazione Positiva & Empatia Strategica',
        targetHours: 40,
        tasks: [
          { title: 'Studiare Paul McKenna per visualizzazione positiva', hours: 15 },
          { title: 'Creare script audio personale di visualizzazione', hours: 25 },
        ],
      },
    ],
    keyResults: [
      { title: '50 interazioni sociali con feedback', targetValue: 50, unit: 'sessions' },
      { title: '20 sessioni voce registrate', targetValue: 20, unit: 'sessions' },
      { title: '1 shooting brand personale completato', targetValue: 1, unit: 'tasks' },
    ],
  });
}

// ============================================================================
// SUITE
// ============================================================================

export interface GoalArchitectFixtureSuite {
  work: GoalArchitectureDraft;
  chess: GoalArchitectureDraft;
  modelPhysique: GoalArchitectureDraft;
  intelligenceEngine: GoalArchitectureDraft;
  presenceUpgrade: GoalArchitectureDraft;
}

export function createAllGoalArchitectFixtures(): GoalArchitectFixtureSuite {
  return {
    work: createWorkGoalDraftFixture(),
    chess: createChessGoalDraftFixture(),
    modelPhysique: createModelPhysiqueGoalDraftFixture(),
    intelligenceEngine: createIntelligenceEngineGoalDraftFixture(),
    presenceUpgrade: createPresenceUpgradeGoalDraftFixture(),
  };
}
