// src/lib/weeklyPlanner/analytics.test.ts
import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import {
  calculateWpiWeeklyAnalytics,
  extractWpiKey,
  findMatchingDraftForWeek,
  getTimeBlockDurationMinutes,
  getWeekRange,
  groupWpiTimeBlocksByDraft,
  isTimeBlockInWeek,
  isWpiTimeBlock,
  parseWpiKey,
  type WpiTimeBlockSnapshot,
} from './analytics';
import {
  draftBlockToTimeBlockInput,
  saveWeeklyPlanDraft,
} from './index';
import { generateWeeklyDraft } from './scheduler';

// ============================================================================
// FIXTURES
// ============================================================================

const WEEK = '2026-01-05'; // Monday
const USER = 'test-user';

function buildSampleDraftWithCommitted() {
  const { draft } = generateWeeklyDraft({
    raw: {
      id: 'raw-analytics',
      text: 'Lunedì Catalana 2 ore. Martedì Catalana 1 ora.',
      weekStartISO: WEEK,
      createdAtISO: '2026-01-04T20:00:00.000Z',
    },
    goals: [{ id: 'g_chess', title: 'Chess Mastery' }],
    projects: [{ id: 'p_openings', title: 'Openings', goalId: 'g_chess' }],
    tasks: [
      {
        id: 't_catalan',
        title: 'Catalan Course',
        projectId: 'p_openings',
        goalId: 'g_chess',
      },
    ],
  });

  // Materialize each committable block into the TimeBlock-shaped snapshot.
  const wpiBlocks: WpiTimeBlockSnapshot[] = draft.blocks
    .filter((b) => b.mapping?.status === 'mapped')
    .map((b, i) => {
      const payload = draftBlockToTimeBlockInput(b, draft);
      return {
        id: `tb_${i}`,
        title: payload.title,
        startTime: payload.startTime,
        endTime: payload.endTime,
        status: 'planned',
        type: payload.type,
        notes: payload.notes,
        taskId: payload.taskId,
        projectId: payload.projectId,
        goalId: payload.goalId,
      };
    });
  return { draft, wpiBlocks };
}

// ============================================================================
// WPI_KEY parsing
// ============================================================================

describe('extractWpiKey / parseWpiKey', () => {
  it('extracts the WPI key from multi-line notes', () => {
    const notes =
      'Generated by Weekly Planning Intelligence.\n' +
      'Source: Lunedì Catalana 2 ore.\n' +
      'WPI_KEY: wpi:draft_abc:draftblock_xyz';
    expect(extractWpiKey(notes)).toBe('wpi:draft_abc:draftblock_xyz');
  });

  it('returns null when notes are undefined / empty / malformed', () => {
    expect(extractWpiKey(undefined)).toBeNull();
    expect(extractWpiKey('')).toBeNull();
    expect(extractWpiKey('no key in this string')).toBeNull();
    expect(extractWpiKey('WPI_KEY: not-a-wpi-format')).toBeNull();
  });

  it('parseWpiKey splits draftId and blockId', () => {
    const parsed = parseWpiKey('wpi:draft_abc:draftblock_xyz');
    expect(parsed).toEqual({
      key: 'wpi:draft_abc:draftblock_xyz',
      draftId: 'draft_abc',
      blockId: 'draftblock_xyz',
    });
  });

  it('parseWpiKey returns null on malformed input', () => {
    expect(parseWpiKey('not-a-key')).toBeNull();
    expect(parseWpiKey('wpi:')).toBeNull();
    expect(parseWpiKey('wpi:only-one-segment')).toBeNull();
  });

  it('isWpiTimeBlock returns true only when notes contain a valid key', () => {
    expect(
      isWpiTimeBlock({ notes: 'WPI_KEY: wpi:d:b' }),
    ).toBe(true);
    expect(isWpiTimeBlock({ notes: 'no key' })).toBe(false);
    expect(isWpiTimeBlock({})).toBe(false);
  });
});

describe('groupWpiTimeBlocksByDraft', () => {
  it('groups blocks by draftId and ignores untagged blocks', () => {
    const blocks: WpiTimeBlockSnapshot[] = [
      {
        id: 'a',
        title: 'A',
        startTime: new Date(),
        endTime: new Date(),
        notes: 'WPI_KEY: wpi:draft1:b1',
      },
      {
        id: 'b',
        title: 'B',
        startTime: new Date(),
        endTime: new Date(),
        notes: 'WPI_KEY: wpi:draft1:b2',
      },
      {
        id: 'c',
        title: 'C',
        startTime: new Date(),
        endTime: new Date(),
        notes: 'WPI_KEY: wpi:draft2:b1',
      },
      {
        id: 'd',
        title: 'D',
        startTime: new Date(),
        endTime: new Date(),
      },
    ];
    const grouped = groupWpiTimeBlocksByDraft(blocks);
    expect(Object.keys(grouped).sort()).toEqual(['draft1', 'draft2']);
    expect(grouped.draft1.blocks).toHaveLength(2);
    expect(grouped.draft2.blocks).toHaveLength(1);
  });
});

// ============================================================================
// week / time helpers
// ============================================================================

describe('getWeekRange', () => {
  it('returns Monday 00:00 to next Monday 00:00 (half-open)', () => {
    const { start, end } = getWeekRange('2026-01-05');
    expect(start.getFullYear()).toBe(2026);
    expect(start.getMonth()).toBe(0);
    expect(start.getDate()).toBe(5);
    expect(start.getHours()).toBe(0);
    expect(end.getDate()).toBe(12);
  });

  it('throws on malformed weekStartISO', () => {
    expect(() => getWeekRange('nope')).toThrow();
  });
});

describe('isTimeBlockInWeek', () => {
  it('returns true for a Date inside the week and false for outside', () => {
    expect(
      isTimeBlockInWeek(
        { startTime: new Date(2026, 0, 5, 9, 0) },
        '2026-01-05',
      ),
    ).toBe(true);
    expect(
      isTimeBlockInWeek(
        { startTime: new Date(2026, 0, 11, 23, 59) },
        '2026-01-05',
      ),
    ).toBe(true);
    expect(
      isTimeBlockInWeek(
        { startTime: new Date(2026, 0, 12, 0, 0) },
        '2026-01-05',
      ),
    ).toBe(false);
    expect(
      isTimeBlockInWeek(
        { startTime: new Date(2026, 0, 4, 23, 59) },
        '2026-01-05',
      ),
    ).toBe(false);
  });

  it('accepts ISO strings', () => {
    expect(
      isTimeBlockInWeek(
        { startTime: '2026-01-06T10:00:00.000Z' },
        '2026-01-05',
      ),
    ).toBe(true);
  });
});

describe('getTimeBlockDurationMinutes', () => {
  it('returns minute difference between start and end', () => {
    const s = new Date(2026, 0, 5, 9, 0);
    const e = new Date(2026, 0, 5, 10, 30);
    expect(
      getTimeBlockDurationMinutes({ startTime: s, endTime: e }),
    ).toBe(90);
  });

  it('returns 0 on inverted or malformed dates', () => {
    expect(
      getTimeBlockDurationMinutes({
        startTime: new Date(2026, 0, 5, 10),
        endTime: new Date(2026, 0, 5, 9),
      }),
    ).toBe(0);
    expect(
      getTimeBlockDurationMinutes({
        startTime: 'bad-date',
        endTime: 'bad-date',
      }),
    ).toBe(0);
  });
});

// ============================================================================
// calculateWpiWeeklyAnalytics — happy path + statuses
// ============================================================================

describe('calculateWpiWeeklyAnalytics', () => {
  it('counts only WPI-tagged blocks inside the week', () => {
    const { draft, wpiBlocks } = buildSampleDraftWithCommitted();
    // Add a non-WPI block to confirm it's ignored.
    const noise: WpiTimeBlockSnapshot = {
      id: 'noise',
      title: 'Manual TimeBlock',
      startTime: new Date(2026, 0, 5, 14, 0),
      endTime: new Date(2026, 0, 5, 15, 0),
      status: 'completed',
      notes: 'no key here',
    };
    const result = calculateWpiWeeklyAnalytics({
      allTimeBlocks: [...wpiBlocks, noise],
      weekStartISO: WEEK,
      matchedDraft: draft,
    });
    expect(result.weekly.generatedBlocks).toBe(wpiBlocks.length);
    expect(result.weekly.generatedBlocks).toBeGreaterThan(0);
    expect(result.wpiBlocks).toHaveLength(wpiBlocks.length);
  });

  it('classifies statuses: completed/overrun → completed, cancelled → missed, planned/in_progress → pending', () => {
    const { draft, wpiBlocks } = buildSampleDraftWithCommitted();
    if (wpiBlocks.length < 4) return;
    const withStatuses = wpiBlocks.map((b, i) => {
      const status =
        i === 0
          ? 'completed'
          : i === 1
            ? 'overrun'
            : i === 2
              ? 'cancelled'
              : 'planned';
      return { ...b, status };
    });
    const result = calculateWpiWeeklyAnalytics({
      allTimeBlocks: withStatuses,
      weekStartISO: WEEK,
      matchedDraft: draft,
    });
    expect(result.weekly.completedBlocks).toBe(2);
    expect(result.weekly.missedBlocks).toBe(1);
    expect(result.weekly.plannedBlocks).toBeGreaterThanOrEqual(1);
  });

  it('reports goal coverage and average block minutes', () => {
    const { draft, wpiBlocks } = buildSampleDraftWithCommitted();
    const result = calculateWpiWeeklyAnalytics({
      allTimeBlocks: wpiBlocks,
      weekStartISO: WEEK,
      matchedDraft: draft,
    });
    expect(result.weekly.goalCoverageRate).toBe(1);
    expect(result.weekly.averageBlockMinutes).toBeGreaterThan(0);
    expect(result.weekly.totalPlannedMinutes).toBeGreaterThan(0);
  });

  it('partialBlocks is always 0 because TimeBlockStatus has no partial', () => {
    const { draft, wpiBlocks } = buildSampleDraftWithCommitted();
    const result = calculateWpiWeeklyAnalytics({
      allTimeBlocks: wpiBlocks,
      weekStartISO: WEEK,
      matchedDraft: draft,
    });
    expect(result.weekly.partialBlocks).toBe(0);
    expect(
      result.weekly.notes.some((n) => /partial/i.test(n)),
    ).toBe(true);
  });

  it('day breakdown sums to totalPlannedMinutes', () => {
    const { draft, wpiBlocks } = buildSampleDraftWithCommitted();
    const result = calculateWpiWeeklyAnalytics({
      allTimeBlocks: wpiBlocks,
      weekStartISO: WEEK,
      matchedDraft: draft,
    });
    const sumDays = (
      [0, 1, 2, 3, 4, 5, 6] as const
    ).reduce(
      (acc, d) => acc + result.weekly.dayBreakdown[d].plannedMinutes,
      0,
    );
    expect(sumDays).toBe(result.weekly.totalPlannedMinutes);
  });
});

// ============================================================================
// calibration
// ============================================================================

describe('calibration', () => {
  it('insufficient_data when fewer than 3 blocks', () => {
    const { draft } = buildSampleDraftWithCommitted();
    const result = calculateWpiWeeklyAnalytics({
      allTimeBlocks: [],
      weekStartISO: WEEK,
      matchedDraft: draft,
    });
    expect(result.calibration.label).toBe('insufficient_data');
  });

  it('insufficient_data when no draft is available even with blocks', () => {
    // Build at least 3 blocks but pass no matchedDraft.
    const blocks: WpiTimeBlockSnapshot[] = Array.from({ length: 3 }).map(
      (_, i) => ({
        id: `b${i}`,
        title: 't',
        startTime: new Date(2026, 0, 5 + i, 9, 0),
        endTime: new Date(2026, 0, 5 + i, 10, 0),
        status: 'completed',
        notes: `WPI_KEY: wpi:d:bx${i}`,
      }),
    );
    const result = calculateWpiWeeklyAnalytics({
      allTimeBlocks: blocks,
      weekStartISO: WEEK,
    });
    expect(result.calibration.label).toBe('insufficient_data');
  });

  function buildCalibrationCase(opts: {
    predictedScore: number;
    completedCount: number;
    totalCount: number;
  }) {
    const blocks: WpiTimeBlockSnapshot[] = Array.from({
      length: opts.totalCount,
    }).map((_, i) => ({
      id: `b${i}`,
      title: `Block ${i}`,
      startTime: new Date(2026, 0, 5 + (i % 7), 9, 0),
      endTime: new Date(2026, 0, 5 + (i % 7), 10, 0),
      status: i < opts.completedCount ? 'completed' : 'cancelled',
      notes: `WPI_KEY: wpi:d:bx${i}`,
    }));
    const draft = {
      id: 'd',
      weekStartISO: WEEK,
      sourceIntent: {
        id: 'r',
        text: 'x',
        weekStartISO: WEEK,
        createdAtISO: '',
      },
      parsedIntents: [],
      blocks: [],
      conflicts: [],
      warnings: [],
      realismScore: {
        overallScore: opts.predictedScore,
        totalPlannedMinutes: 0,
        dailyLoadMinutes: { 0: 0, 1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0 },
        weeklyOverloadPenalty: 0,
        dailyOverloadPenalty: 0,
        contextSwitchPenalty: 0,
        conflictPenalty: 0,
        recoveryPenalty: 0,
        goalCoverageScore: 100,
        notes: [],
      },
      generatedAtISO: '',
      status: 'draft' as const,
    };
    return calculateWpiWeeklyAnalytics({
      allTimeBlocks: blocks,
      weekStartISO: WEEK,
      matchedDraft: draft,
    });
  }

  it('well_calibrated when |actual - predicted| <= 15', () => {
    const r = buildCalibrationCase({
      predictedScore: 70,
      completedCount: 7,
      totalCount: 10,
    }); // actual = 70%
    expect(r.calibration.label).toBe('well_calibrated');
  });

  it('overestimated when predicted > actual + 15', () => {
    const r = buildCalibrationCase({
      predictedScore: 90,
      completedCount: 4,
      totalCount: 10,
    }); // actual = 40%
    expect(r.calibration.label).toBe('overestimated');
    expect(r.calibration.calibrationGap).toBeLessThan(-15);
  });

  it('underestimated when actual > predicted + 15', () => {
    const r = buildCalibrationCase({
      predictedScore: 40,
      completedCount: 9,
      totalCount: 10,
    }); // actual = 90%
    expect(r.calibration.label).toBe('underestimated');
    expect(r.calibration.calibrationGap).toBeGreaterThan(15);
  });
});

// ============================================================================
// findMatchingDraftForWeek
// ============================================================================

describe('findMatchingDraftForWeek', () => {
  beforeEach(() => {
    window.localStorage.clear();
  });
  afterEach(() => {
    window.localStorage.clear();
  });

  it('returns the saved draft when no draftIdsInPlay is provided', () => {
    const { draft } = generateWeeklyDraft({
      raw: {
        id: 'r',
        text: 'Lunedì Catalana 2 ore.',
        weekStartISO: WEEK,
        createdAtISO: '2026-01-04T00:00:00.000Z',
      },
      goals: [],
      projects: [],
      tasks: [],
    });
    saveWeeklyPlanDraft({ userIdOrLocal: USER, weekStartISO: WEEK, draft });
    const found = findMatchingDraftForWeek({
      userIdOrLocal: USER,
      weekStartISO: WEEK,
    });
    expect(found?.id).toBe(draft.id);
  });

  it('returns undefined when no draft is saved', () => {
    expect(
      findMatchingDraftForWeek({
        userIdOrLocal: USER,
        weekStartISO: WEEK,
      }),
    ).toBeUndefined();
  });

  it('returns the saved draft when its id is in the draftIdsInPlay set', () => {
    const { draft } = generateWeeklyDraft({
      raw: {
        id: 'r',
        text: 'Lunedì Catalana 2 ore.',
        weekStartISO: WEEK,
        createdAtISO: '2026-01-04T00:00:00.000Z',
      },
      goals: [],
      projects: [],
      tasks: [],
    });
    saveWeeklyPlanDraft({ userIdOrLocal: USER, weekStartISO: WEEK, draft });
    const found = findMatchingDraftForWeek({
      userIdOrLocal: USER,
      weekStartISO: WEEK,
      draftIdsInPlay: [draft.id],
    });
    expect(found?.id).toBe(draft.id);
  });

  it('returns undefined when WPI blocks reference a different draftId', () => {
    const { draft } = generateWeeklyDraft({
      raw: {
        id: 'r',
        text: 'Lunedì Catalana 2 ore.',
        weekStartISO: WEEK,
        createdAtISO: '2026-01-04T00:00:00.000Z',
      },
      goals: [],
      projects: [],
      tasks: [],
    });
    saveWeeklyPlanDraft({ userIdOrLocal: USER, weekStartISO: WEEK, draft });
    expect(
      findMatchingDraftForWeek({
        userIdOrLocal: USER,
        weekStartISO: WEEK,
        draftIdsInPlay: ['some-other-id'],
      }),
    ).toBeUndefined();
  });
});
